### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by nobleess** [Petr09Mitin/technopark-go-dz2#1]
https://github.com/Petr09Mitin/technopark-go-dz2/blob/1bf21927cb34d83fb365ce4f42a04e7ca490cb61/spammer.go#L21

В чем смысл идти в обратном порядке

**Comment by nobleess** [comment]
@Petr09Mitin

**Comment by Petr09Mitin** [comment]
@grop4all начинаем с последней по очередности функции, запускаем ее в горутину ждать результата предпоследней, в следующей итерации цикла запускаем предпоследнюю ждать результата предыдущей и так далее. В конце концов запускаем самую первую, которая ни обо что не блокируется, и эта цепочка вызовов начинает сворачиваться в обратном порядке.

**Comment by nobleess** [comment]
@Petr09Mitin спасибо
